version: '3.3'

services:
  mariadb:
    container_name: mariadb
    image: mariadb:lts
    env_file:
      - .env
    ports:
      - '3306:3306'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      # - ALLOW_EMPTY_PASSWORD=yes
      - 'MARIADB_USER=$DB_USERNAME'
      - 'MARIADB_PASSWORD=$DB_PASSWORD'
      - 'MARIADB_ROOT_PASSWORD=$DB_PASSWORD'
      - 'MARIADB_DATABASE=$DB_NAME'
    volumes:
      - './data:/var/lib/mysql:rw'
    networks:
      - mariadb_network
    restart: always

networks:
  mariadb_network:
    external: true
